site_name: ICAN Training
site_description: Data Analytics Training at ICAN

nav:
  - Getting Started: index.md
  - Introduction:
    - DS, ML & AI Overview: ican/00_Intro_DS_ML_AI_for_CA.md
  - Basics:
    - Python Basics: ican/01_Python_for_CA_Beginners.md
    - Numpy: ican/02_NumPy_for_CA.md
    - Pandas: ican/03_Pandas_for_CA.md
    - Matplotlib: ican/04_Matplotlib_for_CA.md
    - Seaborn: ican/05_Seaborn_for_CA.md
  - Data Analytics:
    - CRISP-DM Process: ican/06_CRISP_DM_for_CA.md
    - Data Cleaning: ican/07_Data_Cleaning_for_CA.md
    - Feature Engineering: ican/08_Feature_Engineering_for_CA.md
    - Regression & Classification: ican/09_Regression_Classification_for_CA.md
    - Clustering & K-Means: ican/10_Clustering_for_CA.md



theme:
  # name: material
  name: readthedocs
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
  code:
    highlighting: true
    light: default
    dark: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra:
  generator: false

copyright: Copyright &copy; 2025 - Aayush Raj Regmi
