site_name: ICANN Training
site_description: Data Analytics Training at ICANN

nav:
  - Python Basics: index.md
  - Numpy Basics: icann/00a_numpy_basics.md
    

theme:
  # name: material
  name: readthedocs
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
  code:
    highlighting: true
    light: default
    dark: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences  
extra:
  generator: false
      
copyright: Copyright &copy; 2025 - Aayush Raj Regmi
